//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stoffi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double WinHeight {
            get {
                return ((double)(this["WinHeight"]));
            }
            set {
                this["WinHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double WinWidth {
            get {
                return ((double)(this["WinWidth"]));
            }
            set {
                this["WinWidth"] = value;
            }
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public double WinTop
		{
			get
			{
				return ((double)(this["WinTop"]));
			}
			set
			{
				this["WinTop"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public double WinLeft
		{
			get
			{
				return ((double)(this["WinLeft"]));
			}
			set
			{
				this["WinLeft"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Normal")]
		public string WinState
		{
			get
			{
				return ((string)(this["WinState"]));
			}
			set
			{
				this["WinState"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("200")]
		public double EqualizerHeight
		{
			get
			{
				return ((double)(this["EqualizerHeight"]));
			}
			set
			{
				this["EqualizerHeight"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("415")]
		public double EqualizerWidth
		{
			get
			{
				return ((double)(this["EqualizerWidth"]));
			}
			set
			{
				this["EqualizerWidth"] = value;
			}
		}
        
        [global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("-1")]
		public double EqualizerTop
		{
            get {
				return ((double)(this["EqualizerTop"]));
            }
            set {
				this["EqualizerTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("-1")]
		public double EqualizerLeft
		{
            get {
				return ((double)(this["EqualizerLeft"]));
            }
            set {
				this["EqualizerLeft"] = value;
            }
        }

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Stopped")]
		public MediaState MediaState
		{
			get
			{
				return ((MediaState)(this["MediaState"]));
			}
			set
			{
				this["MediaState"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public string Language
		{
			get
			{
				return ((string)(this["Language"]));
			}
			set
			{
				this["Language"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("150")]
		public double NavigationPaneWidth
		{
			get
			{
				return ((double)(this["NavigationPaneWidth"]));
			}
			set
			{
				this["NavigationPaneWidth"] = value;
			}
		}

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double DetailsPaneHeight
        {
            get
            {
                return ((double)(this["DetailsPaneHeight"]));
            }
            set
            {
                this["DetailsPaneHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoRepeat")]
        public RepeatState Repeat {
            get {
				return ((RepeatState)(this["Repeat"]));
            }
            set {
                this["Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Shuffle {
            get {
                return ((bool)(this["Shuffle"]));
            }
            set {
                this["Shuffle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double Volume {
            get {
                return ((double)(this["Volume"]));
            }
            set {
                this["Volume"] = value;
            }
        }

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public System.Collections.Generic.List<EqualizerProfile> EqualizerProfiles
		{
			get
			{
				return ((System.Collections.Generic.List<EqualizerProfile>)(this["EqualizerProfiles"]));
			}
			set
			{
				this["EqualizerProfiles"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public EqualizerProfile CurrentEqualizerProfile
		{
			get
			{
				return ((EqualizerProfile)(this["CurrentEqualizerProfile"]));
			}
			set
			{
				this["CurrentEqualizerProfile"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public double Seek
		{
			get
			{
				return ((double)(this["Seek"]));
			}
			set
			{
				this["Seek"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public TrackData CurrentTrack
		{
			get
			{
				return ((TrackData)(this["CurrentTrack"]));
			}
			set
			{
				this["CurrentTrack"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int HistoryIndex
		{
			get
			{
				return ((int)(this["HistoryIndex"]));
			}
			set
			{
				this["HistoryIndex"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Files")]
		public string CurrentSelectedNavigation
		{
			get
			{
				return ((string)(this["CurrentSelectedNavigation"]));
			}
			set
			{
				this["CurrentSelectedNavigation"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Files")]
		public string CurrentActiveNavigation
		{
			get
			{
				return ((string)(this["CurrentActiveNavigation"]));
			}
			set
			{
				this["CurrentActiveNavigation"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public string CurrentVisualizer
		{
			get
			{
				return ((string)(this["CurrentVisualizer"]));
			}
			set
			{
				this["CurrentVisualizer"] = value;
			}
		}
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
		public bool MenuBarVisible
		{
            get {
                return (bool)(this["MenuBarVisible"]);
            }
            set {
				this["MenuBarVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
		public bool DetailsPaneVisible
		{
            get {
                return (bool)(this["DetailsPaneVisible"]);
            }
            set {
				this["DetailsPaneVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.ObjectModel.ObservableCollection<Core.PluginItem> Plugins
        {
            get
            {
                return ((global::System.Collections.ObjectModel.ObservableCollection<Core.PluginItem>)(this["Plugins"]));
            }
            set
            {
                this["Plugins"] = value;
            }
        }

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public global::System.Collections.Generic.List<PluginSettings> PluginSettings
		{
			get
			{
				return ((global::System.Collections.Generic.List<PluginSettings>)(this["PluginSettings"]));
			}
			set
			{
				this["PluginSettings"] = value;
			}
		}

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ViewDetailsConfig PluginListConfig
        {
            get
            {
                return ((ViewDetailsConfig)(this["PluginListConfig"]));
            }
            set
            {
                this["PluginListConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public global::System.Collections.ObjectModel.ObservableCollection<SourceData> Sources
		{
            get {
                return ((global::System.Collections.ObjectModel.ObservableCollection<SourceData>)(this["Sources"]));
            }
            set {
                this["Sources"] = value;
            }
        }

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public ViewDetailsConfig SourceListConfig
		{
			get
			{
				return ((ViewDetailsConfig)(this["SourceListConfig"]));
			}
			set
			{
				this["SourceListConfig"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public ViewDetailsConfig FileListConfig
		{
			get
			{
				return ((ViewDetailsConfig)(this["FileListConfig"]));
			}
			set
			{
				this["FileListConfig"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public ViewDetailsConfig RadioListConfig
		{
			get
			{
				return ((ViewDetailsConfig)(this["RadioListConfig"]));
			}
			set
			{
				this["RadioListConfig"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public ViewDetailsConfig DiscListConfig
		{
			get
			{
				return ((ViewDetailsConfig)(this["DiscListConfig"]));
			}
			set
			{
				this["DiscListConfig"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public ViewDetailsConfig HistoryListConfig
		{
			get
			{
				return ((ViewDetailsConfig)(this["HistoryListConfig"]));
			}
			set
			{
				this["HistoryListConfig"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public ViewDetailsConfig QueueListConfig
		{
			get
			{
				return ((ViewDetailsConfig)(this["QueueListConfig"]));
			}
			set
			{
				this["QueueListConfig"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public ViewDetailsConfig YouTubeListConfig
		{
			get
			{
				return ((ViewDetailsConfig)(this["YouTubeListConfig"]));
			}
			set
			{
				this["YouTubeListConfig"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public ViewDetailsConfig SoundCloudListConfig
		{
			get
			{
				return ((ViewDetailsConfig)(this["SoundCloudListConfig"]));
			}
			set
			{
				this["SoundCloudListConfig"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public global::System.Collections.ObjectModel.ObservableCollection<TrackData> FileTracks
		{
			get
			{
				return (global::System.Collections.ObjectModel.ObservableCollection<TrackData>)(this["FileTracks"]);
			}
			set
			{
				this["FileTracks"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public global::System.Collections.ObjectModel.ObservableCollection<TrackData> RadioTracks
		{
			get
			{
				return (global::System.Collections.ObjectModel.ObservableCollection<TrackData>)(this["RadioTracks"]);
			}
			set
			{
				this["RadioTracks"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public global::System.Collections.ObjectModel.ObservableCollection<TrackData> HistoryTracks
		{
			get
			{
				return (global::System.Collections.ObjectModel.ObservableCollection<TrackData>)(this["HistoryTracks"]);
			}
			set
			{
				this["HistoryTracks"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public global::System.Collections.ObjectModel.ObservableCollection<TrackData> QueueTracks
		{
			get
			{
				return (global::System.Collections.ObjectModel.ObservableCollection<TrackData>)(this["QueueTracks"]);
			}
			set
			{
				this["QueueTracks"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public global::System.Collections.Generic.List<global::Stoffi.PlaylistData> Playlists
		{
			get
			{
				return ((global::System.Collections.Generic.List<global::Stoffi.PlaylistData>)(this["Playlists"]));
			}
			set
			{
				this["Playlists"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Library")]
		public OpenAddPolicy OpenAddPolicy
		{
			get
			{
				return ((OpenAddPolicy)(this["OpenAddPolicy"]));
			}
			set
			{
				this["OpenAddPolicy"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("BackOfQueue")]
		public OpenPlayPolicy OpenPlayPolicy
		{
			get
			{
				return ((OpenPlayPolicy)(this["OpenPlayPolicy"]));
			}
			set
			{
				this["OpenPlayPolicy"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Automatic")]
		public Stoffi.UpgradePolicy UpgradePolicy
		{
			get
			{
				return ((Stoffi.UpgradePolicy)(this["UpgradePolicy"]));
			}
			set
			{
				this["UpgradePolicy"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Individual")]
		public Stoffi.SearchPolicy SearchPolicy
		{
			get
			{
				return ((Stoffi.SearchPolicy)(this["SearchPolicy"]));
			}
			set
			{
				this["SearchPolicy"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("True")]
		public bool ShowOSD
		{
			get
			{
				return ((bool)(this["ShowOSD"]));
			}
			set
			{
				this["ShowOSD"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool MinimizeToTray
		{
			get
			{
				return ((bool)(this["MinimizeToTray"]));
			}
			set
			{
				this["MinimizeToTray"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public int ID
		{
			get
			{
				return ((int)(this["ID"]));
			}
			set
			{
				this["ID"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public long Version
		{
			get
			{
				return 1404671946; // version
			}
			set
			{
                this["Version"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public string Architecture
		{
			get
			{
				return "32";
			}
			set
			{
				this["Architecture"] = value;
			}
		}

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Channel
        {
            get
            {
				return "stable"; // channel
            }
            set
            {
                this["Channel"] = value;
            }
        }

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public string Release
		{
			get
			{
				return "Qin";
			}
			set
			{
				this["Release"] = value;
			}
		}

        [global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long UpgradeCheck
        {
            get
            {
                return ((long)(this["UpgradeCheck"]));
            }
            set
            {
                this["UpgradeCheck"] = value;
            }
        }

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public global::System.Collections.Generic.List<KeyboardShortcutProfile> ShortcutProfiles
		{
			get
			{
				return ((global::System.Collections.Generic.List<KeyboardShortcutProfile>)(this["ShortcutProfiles"]));
			}
			set
			{
				this["ShortcutProfiles"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Stoffi")]
		public string CurrentShortcutProfile
		{
			get
			{
				return ((string)(this["CurrentShortcutProfile"]));
			}
			set
			{
				this["CurrentShortcutProfile"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public string OAuthToken
		{
			get
			{
				return ((string)(this["OAuthToken"]));
			}
			set
			{
				this["OAuthToken"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public string OAuthSecret
		{
			get
			{
				return ((string)(this["OAuthSecret"]));
			}
			set
			{
				this["OAuthSecret"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("true")]
		public bool SubmitSongs
		{
			get
			{
				return ((bool)(this["SubmitSongs"]));
			}
			set
			{
				this["SubmitSongs"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("true")]
		public bool PauseWhenLocked
		{
			get
			{
				return ((bool)(this["PauseWhenLocked"]));
			}
			set
			{
				this["PauseWhenLocked"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("false")]
		public bool PauseWhenSongEnds
		{
			get
			{
				return ((bool)(this["PauseWhenSongEnds"]));
			}
			set
			{
				this["PauseWhenSongEnds"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public System.Collections.Generic.List<CloudIdentity> CloudIdentities
		{
			get
			{
				return ((System.Collections.Generic.List<CloudIdentity>)(this["CloudIdentities"]));
			}
			set
			{
				this["CloudIdentities"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		public System.Collections.Generic.Dictionary<string, System.Tuple<string, string>> ListenBuffer
		{
			get
			{
				return ((System.Collections.Generic.Dictionary<string, System.Tuple<string, string>>)(this["ListenBuffer"]));
			}
			set
			{
				this["ListenBuffer"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Music")]
		public string YouTubeFilter
		{
			get
			{
				return ((string)(this["YouTubeFilter"]));
			}
			set
			{
				this["YouTubeFilter"] = value;
			}
		}

		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("Automatic")]
		public string YouTubeQuality
		{
			get
			{
				return ((string)(this["YouTubeQuality"]));
			}
			set
			{
				this["YouTubeQuality"] = value;
			}
		}
    }
}
